[colors]
foreground = "#F8F8F3"
background = "#06080B"
cursor_bg = "#8FB6C2"
cursor_fg = "#06080B"
cursor_border = "#8FB6C2"
selection_fg = "#F8F8F3"
selection_bg = "#8FB6C2"
scrollbar_thumb = "#8FB6C2"
split = "#8FB6C2"
ansi = [
  "#3C3E3F",
  "#B0B1A7",
  "#2FA8AD",
  "#849CA9",
  "#42788F",
  "#1D576C",
  "#0F3344",
  "#ECEDE6",
]
brights = [
  "#A5A6A1",
  "#EAECDE",
  "#3FE0E7",
  "#B0D0E1",
  "#58A0BF",
  "#277490",
  "#14445B",
  "#ECEDE6",
]
